
#通用数据源配置
spring:
  application:
    name: oms-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.116.18.103:1521:ims
    username: oms
    password: oms
  devtools: add-properties=true

#spring:
#  datasource:
#    url: jdbc:mysql://10.16.18.191/mstar?charset=utf8mb4&useSSL=false
#    username: root
#    password: root
#    # driver-class-name: com.mysql.jdbc.Driver


# Hikari 数据源专用配置
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=5
#
## JPA 相关配置
#spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

